# Generated by Django 4.1 on 2023-11-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("touristapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="duration",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
