# Generated by Django 4.1 on 2023-12-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("touristapp", "0002_tour_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("user", models.TextField()),
            ],
        ),
    ]
