# Generated by Django 4.1 on 2024-01-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("touristapp", "0005_reservation_cost_reservation_people"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="photo",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
