# Generated by Django 4.1 on 2024-01-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("touristapp", "0007_tour_days_alter_tour_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="days",
            field=models.IntegerField(blank=True),
        ),
    ]
